// Frontend/react-app/src/ChatWindow.js
import { useState } from 'react';
import "./App.css";

export const ChatWindow = ({ sendRequest }) => {
  const [chatHistory, setChatHistory] = useState([]);
  const [message, setMessage] = useState('');

  const handleSendMessage = async () => {
    if (message.trim() === '') return;
    const startTime = performance.now();
    const response = await sendRequest(message);
    const endTime = performance.now(); 
    const responseTime = endTime - startTime; 

    console.log('Time:', responseTime, '\nRes:', response);
    setChatHistory(prevHistory => [
      ...prevHistory,
      { sender: 'You', message },
      { sender: 'Bot', message: response }
    ]);
    setMessage('');
  };

  const handleKeyPress = event => {
    if (event.key === 'Enter') {
      handleSendMessage();
    }
  };

  return (
    <div className="chat-window-container">
      <div className="chat-message-container">
        {chatHistory.map((chat, index) => (
          <div key={index} className={chat.sender === 'You' ? 'user-message' : 'bot-message'}>
            <strong>{chat.sender}: </strong>{chat.message}
          </div>
        ))}
      </div>
      <div className="message-input-container">
        <textarea
          className="message-input"
          placeholder="Type your message here..."
          value={message}
          onChange={e => setMessage(e.target.value)}
          onKeyDown={handleKeyPress}
        />
        <button className="send-button" onClick={handleSendMessage}>Send</button>
      </div>
    </div>
  );  
}

// Frontend/vue-app/src/components/ChatWindow.vue
<template>
  <div class="chat-window-container">
    <div class="chat-message-container">
      <div v-for="(chat, index) in chatHistory" :key="index" :class="{ 'user-message': chat.sender === 'You', 'bot-message': chat.sender === 'Bot' }">
        <strong>{{ chat.sender }}: </strong>{{ chat.message }}
      </div>
    </div>

    <div class="message-input-container">
      <textarea
        class="message-input"
        placeholder="Type your message here..."
        v-model="message"
        @keypress.enter="handleKeyPress"
      ></textarea>
      <button class="send-button" @click="handleSendMessage">Send</button>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    sendRequest: Function
  },
  data() {
    return {
      chatHistory: [],
      message: ''
    };
  },
  methods: {
    async handleSendMessage() {
      if (this.message.trim() === '') return;
      const startTime = performance.now();
      const response = await this.sendRequest(this.message);
      const endTime = performance.now(); 
      const responseTime = endTime - startTime; 

      console.log('Time:', responseTime, '\nRes:', response);
      this.chatHistory.push({ sender: 'You', message: this.message });
      this.chatHistory.push({ sender: 'Bot', message: response });
      this.message = '';
    },
    handleKeyPress(event) {
      if (event.key === 'Enter') {
        this.handleSendMessage();
      }
    }
  }
};
</script>
