// Frontend/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  template: `
    <div class="App">
      <h3 class="title">Angular AI ChatBot</h3>
      <app-chat-window [sendRequest]="sendRequest"></app-chat-window>
    </div>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  sendRequest: (message: string) => Promise<string>;

  constructor(private http: HttpClient) {
    this.sendRequest = async (message: string) => {
      try {
        const response = await this.http.post("http://localhost:5000/api", { message }).toPromise();
        return response as string;
      } catch (error) {
        console.error("Error:", error);
        return 'Failed to generate response!';
      }
    };
  }
}

// Frontend/react-app/src/App.js
import { ChatWindow } from './ChatWindow.js'

function App() {

  const sendRequest = async (message) => {
    try {
      const response = await fetch("http://localhost:5000/api", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ message })
      });
      const data = await response.json();
      return data;
    } catch (error) {
      console.error("Error:", error);
      return 'Failed to generate response!';
    }
  };

  return (
    <div className="App">
      <h3 className="title">React AI ChatBot</h3>
      <ChatWindow sendRequest={sendRequest} />
    </div>
  );
}

export default App;
